### ISSUE TITLE
Not work minify and pretty. SVGO 2.8 Atom 1.15

### ISSUE THREAD

**Issue by Toxblh** [1000ch/atom-svgo#10]
I do minify svg and have error. This is simply svg, and when I do minify in terminal with svgo - all good.
<img width="2239" alt="screen shot 2017-03-14 at 15 16 08" src="https://cloud.githubusercontent.com/assets/2198153/23900233/72be5410-08c9-11e7-84f2-672655c6cea3.png">

**Comment by RossBarnie** [comment]
Offending line is https://github.com/1000ch/atom-svgo/blob/master/index.js#L43. When you don't specify a "disable" option in your settings the command line argument that is constructed is invalid (ie `--disable=<empty string>`).

We're commenting out that line as a workaround.

**Comment by 1000ch** [comment]
@Toxblh @RossBarnie Please update to `v2.8.1` 🙏

**Comment by Toxblh** [comment]
Great! All work :)
