### ISSUE TITLE
Add --pretty option

### ISSUE THREAD

**Issue by jaydenseric** [1000ch/atom-svgo#2]
Thanks for the neat plugin. Adding the ability to use the SVGO `--pretty` option would double the usefulness. When I have an SVG open in Atom it is usually because I need to manually work it before and after running SVGO, for example add a missing `<title>`, strip unnecessary fills, convert `<g>` to `<symbol>` and paste in other layers, etc.

**Comment by 1000ch** [comment]
Sounds good. Should it be set as plugin setting in **Settings > Packages > svgo Settings** ? or adding menu into context menu "Minify SVG (--pretty)"?

**Comment by jaydenseric** [comment]
How about both an extra key (Shift key?) when running the keyboard shortcut, and a second context menu option.

**Comment by 1000ch** [comment]
Try `v1.1.0`!
44f55c9b302f28fc3dfdac16530483cdd887b623

**Comment by jaydenseric** [comment]
Truly awesome turnaround time, the context menu options work great!

For some reason, neither of the keyboard shortcuts are working. Also, in the menu options the keyboard shortcut only displays for Minify:

<img width="481" alt="screen shot 2016-03-18 at 7 41 27 pm" src="https://cloud.githubusercontent.com/assets/1754873/13872935/10181d44-ed42-11e5-9114-a69af010b1e7.png">
