### ISSUE TITLE
svgo ENOENT

### ISSUE THREAD

**Issue by jerone** [1000ch/atom-svgo#5]
I just installed this package and it is erroring on me every time I minify or prettify an SVG file:

```
Error: spawn C:\Users\<user>\.atom\packages\svgo\node_modules\.bin\svgo ENOENT(…)(anonymous function) @ /C:/Users/<user>/.atom/packages/svgo/index.js:35
```

----

_Atom 1.7.1
Windows 8.1 x64
svgo 2.0.0_

**Comment by jerone** [comment]
Still happening... Is there anything I can provide?

_Atom 1.8.0
Windows 8.1 x64
svgo 2.0.1_

**Comment by jerone** [comment]
Ah found the issue... [here](https://github.com/1000ch/atom-svgo/blob/master/index.js#L6) you are referencing the `svgo` file in the bin folder, but Windows :checkered_flag: requires the `svgo.cmd` file.

Changing [that line](https://github.com/1000ch/atom-svgo/blob/master/index.js#L6) to the following fixed my issue:
```js
const SVGO_PATH = normalize(join(__dirname, 'node_modules', '.bin', 'svgo.cmd'));
```

**Comment by 1000ch** [comment]
@jerone 
Thank you for reporting and debugging. 
Would you update this package to `v2.1.1` and check still having the error?

**Comment by jerone** [comment]
[**@1000ch**](https://github.com/1000ch) commented on [17 jun. 2016 12:49 CEST](https://github.com/1000ch/atom-svgo/issues/5#issuecomment-226739510 "2016-06-17T10:49:10Z - Replied by Github Reply Comments"):
> [@jerone](https://github.com/jerone)   
> 
> Thank you for reporting and debugging.   
> 
> Would you update this package to `v2.1.1` and check still having the error?

Still failing, which makes sense because the [check for `svgo`](https://github.com/1000ch/atom-svgo/blob/e5d36a99cc3195480dd2b784f1351deb0a9d6ed6/index.js#L7) returns true, because the file exists on Windows too (it's part of that package).

I think an OS check would solve this...

**Comment by 1000ch** [comment]
Ah, this was too bad... Please update again? 🙏

**Comment by jerone** [comment]
:+1: Yes confirmed working!
