### ISSUE TITLE
Is there any way to specify options?

### ISSUE THREAD

**Issue by ianwalter** [1000ch/atom-svgo#9]
It doesn't look like theres any way to set options. I'd like to disable `cleanupIDs`. Maybe there should just be a settings text input that will pass all contents as params to the call?

**Comment by 1000ch** [comment]
No way to specify now. SVGO has many options as plugin, so it's slightly difficult to provide all options from this plugin's setting IF...

**Comment by 1000ch** [comment]
@ianwalter You can now apply disable option on **Setting > Packages > svgo > Disable** with `atom-svgo` v2.8.0 👌
